# Generated by Django 6.1 on 2026-08-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_image_category_image_url_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_at_purchase',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Mumbai', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('UPI', 'UPI / Online')], default='COD', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_mode',
            field=models.CharField(choices=[('instant', 'Instant Delivery (30 Mins)')], default='instant', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceablepincode',
            name='estimated_instant_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='serviceablepincode',
            name='instant_eligible',
            field=models.BooleanField(default=True),
        ),
    ]
